import { createFileRoute } from "@tanstack/react-router";
import { Check, PackageCheck, Users, UtensilsCrossed } from "lucide-react";

import { AppShell, PageIntro } from "@/components/app-shell";

export const Route = createFileRoute("/impact")({ head: () => ({ meta: [{ title: "Community Impact | Food Waste Connect" }, { name: "description", content: "See food rescue and community meal impact totals." }, { property: "og:title", content: "Community Impact | Food Waste Connect" }, { property: "og:description", content: "Track food saved, people fed, and completed pickups." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ImpactPage });

const stats = [{ label: "Total food saved", value: "2,480", unit: "kg", icon: UtensilsCrossed }, { label: "People fed", value: "1,860", unit: "people", icon: Users }, { label: "Donations completed", value: "142", unit: "donations", icon: Check }, { label: "Pickups completed", value: "128", unit: "pickups", icon: PackageCheck }];
const progress = [{ label: "Monthly food rescue goal", value: 82, detail: "410 of 500 kg" }, { label: "Meals delivered on time", value: 94, detail: "94% this month" }, { label: "Donations successfully matched", value: 88, detail: "125 of 142" }];

function ImpactPage() { return <AppShell><PageIntro eyebrow="Impact / September" title={<>Shared effort, <span className="italic">measurable change.</span></>} description="A simple view of the food rescued and community support delivered through the network." /><section className="grid grid-cols-2 border-b border-border xl:grid-cols-4">{stats.map(({label,value,unit,icon:Icon},index)=><article key={label} className={`p-5 sm:p-7 ${index % 2 === 0 ? "border-r border-border" : ""} ${index < 2 ? "border-b border-border xl:border-b-0" : ""} ${index === 1 ? "xl:border-r" : ""}`}><div className="flex items-center justify-between"><p className="label-caps text-muted-foreground">{label}</p><Icon className="size-4 text-accent" /></div><p className="mt-5 font-display text-4xl sm:text-5xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{unit}</p></article>)}</section><section className="p-5 sm:p-8 lg:p-12"><div className="max-w-4xl"><h2 className="font-display text-3xl italic">This month’s progress</h2><div className="mt-8 space-y-8">{progress.map((item)=><div key={item.label}><div className="flex justify-between gap-4 text-sm"><span>{item.label}</span><span className="text-muted-foreground">{item.detail}</span></div><div className="mt-3 h-2 bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${item.value}%`}} /></div></div>)}</div></div></section></AppShell>; }